<?php

function ic_theme_custom_fields() {
	global $pagenow;

	if ( function_exists( 'acf_add_options_page' ) ) {
		acf_add_options_page( array(
			'page_title'  => 'Defined sections',
			'menu_title'  => 'Defined sections',
			'menu_slug'   => 'defined-sections',
			'parent_slug' => 'themes.php',
		) );
	}

	$is_options_page = isset( $_GET['page'] ) && $_GET['page'] == 'defined-sections' && ( 'themes.php' === $pagenow || 'admin.php' === $pagenow );

	$name = $is_options_page ? 'defined_sections' : 'post_content';

	$layouts   = array();
	$layouts[] = array(
		'key'        => '5729a1e96e78b',
		'name'       => 'page-title',
		'label'      => 'Page Title',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5729a27a81c4b',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'           => 'field_5729a1f25ae19',
				'label'         => 'Background Image',
				'name'          => 'background_image',
				'type'          => 'image',
				'return_format' => 'url',
				'preview_size'  => 'large',
				'library'       => 'all',
			),
			array(
				'key'      => 'field_5729a6a8dc07e',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'       => 'field_5729a28581c4c',
				'label'     => 'Heading',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5729a2235ae1a',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729a23d5ae1b',
				'label' => 'Subtitle',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729a2455ae1c',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'       => 'field_5729a28f81c4d',
				'label'     => 'Button',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5729a2ce2742b',
				'label' => 'Label',
				'name'  => 'label',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729a2d92742c',
				'label' => 'Url',
				'name'  => 'url',
				'type'  => 'url',
			),
			array(
				'key'       => 'field_5729a5bcf9b32',
				'label'     => 'Circle',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'           => 'field_5729a5e4ec601',
				'label'         => 'Show circle',
				'name'          => 'circle_status',
				'type'          => 'true_false',
				'message'       => 'Show circle',
				'default_value' => 0,
			),
			array(
				'key'               => 'field_5729a5faec602',
				'label'             => 'Title',
				'name'              => 'circle_title',
				'type'              => 'text',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5729a5e4ec601',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
			),
			array(
				'key'               => 'field_5729a610ec603',
				'label'             => 'Subtitle',
				'name'              => 'circle_subtitle',
				'type'              => 'text',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5729a5e4ec601',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
			),
			array(
				'key'               => 'field_5729a623ec604',
				'label'             => 'Text',
				'name'              => 'circle_text',
				'type'              => 'textarea',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5729a5e4ec601',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);

	$layouts[] = array(
		'key'        => '5729ab41c0c2b',
		'name'       => 'wysiwyg-editor',
		'label'      => 'Wysiwyg Editor',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5729ac53b9265',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'      => 'field_5729ac6bb9266',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),

			array(
				'key'           => 'field_572ddd051e39f',
				'label'         => 'Full width',
				'name'          => 'full_width',
				'type'          => 'true_false',
				'message'       => 'Set as full width section',
				'default_value' => 0,
			),

			array(
				'key'       => 'field_5729ac85b9268',
				'label'     => 'Content',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5a29adab84c82',
				'label' => 'Title',
				'name'  => 'content_title',
				'type'  => 'text',
			),
			array(
				'key'          => 'field_5729ab4fc0c2c',
				'label'        => 'Content',
				'name'         => 'content',
				'type'         => 'wysiwyg',
				'required'     => 1,
				'tabs'         => 'all',
				'toolbar'      => 'full',
				'media_upload' => 1,
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729adab84c80',
		'name'       => 'success-stories',
		'label'      => 'Success Stories',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5729adab84c81',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'      => 'field_5729adab84c82',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'       => 'field_5729adab84c83',
				'label'     => 'Heading',
				'name'      => 'heading',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5729addb84c85',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729ade284c86',
				'label' => 'Subtitle',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729adea84c87',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'       => 'field_5729ae1484c88',
				'label'     => 'Items',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'          => 'field_5729ae2284c89',
				'label'        => 'Success Stories Items',
				'name'         => 'success_stories_items',
				'type'         => 'repeater',
				'required'     => 1,
				'layout'       => 'block',
				'button_label' => 'Add item',
				'sub_fields'   => array(
					array(
						'key'      => 'field_5729ae4784c8a',
						'label'    => 'Title',
						'name'     => 'sc_title',
						'type'     => 'text',
						'required' => 1,
					),
					array(
						'key'          => 'field_5729ae5a84c8b',
						'label'        => 'Content',
						'name'         => 'sc_content',
						'type'         => 'wysiwyg',
						'tabs'         => 'all',
						'toolbar'      => 'full',
						'media_upload' => 1,
					),
					array(
						'key'       => 'field_5729ae7184c8c',
						'label'     => 'Quote',
						'name'      => 'sc_quote',
						'type'      => 'textarea',
						'new_lines' => '',
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729ea4fdcbe3',
		'name'       => 'infrastructure',
		'label'      => 'Infrastructure',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5729ea4fdcbe4',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'      => 'field_5729ea4fdcbe5',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'       => 'field_5729ea4fdcbe6',
				'label'     => 'Heading',
				'name'      => 'heading',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5729ea4fdcbe7',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729ea4fdcbe8',
				'label' => 'Subtitle',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_5729ea4fdcbe9',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'       => 'field_5729ea4fdcbea',
				'label'     => 'Items',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'          => 'field_5729ea4fdcbeb',
				'label'        => 'Infastructure Items',
				'name'         => 'infrastructure_items',
				'type'         => 'repeater',
				'required'     => 1,
				'layout'       => 'block',
				'button_label' => 'Add item',
				'sub_fields'   => array(
					array(
						'key'      => 'field_5729ea4fdcbec',
						'label'    => 'Title',
						'name'     => 'title',
						'type'     => 'text',
						'required' => 1,
					),
					array(
						'key'          => 'field_5729ea4fdcbed',
						'label'        => 'Content',
						'name'         => 'content',
						'type'         => 'wysiwyg',
						'tabs'         => 'all',
						'toolbar'      => 'full',
						'media_upload' => 1,
					),
					array(
						'key'      => 'field_5729eac3dcbef',
						'label'    => 'Location',
						'name'     => 'location',
						'type'     => 'google_map',
						'required' => 1,
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729b7e1b06cc',
		'name'       => 'solutions',
		'label'      => 'Solutions',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'               => 'field_5729b7e1b06cd',
				'label'             => 'Settings',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b7e1b06ce',
				'label'             => 'Section Name',
				'name'              => 'section_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => $is_options_page,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729b7e1b06cf',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b7e1b06d0',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729b7e1b06d1',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'   => 'field_5729b7e1b06d2',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'               => 'field_5729b7e1b06d3',
				'label'             => 'Items',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b7e1b06d4',
				'label'             => 'Solutions',
				'name'              => 'solutions',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add item',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729b7e1b06d5',
						'label'             => 'Title',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729b7e1b06d6',
						'label'             => 'Icon',
						'name'              => 'icon',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_5729b7e1b06d7',
						'label'             => 'Content',
						'name'              => 'content',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => '',
						'rows'              => '',
						'new_lines'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729b90c884a3',
						'label'             => 'Url Label',
						'name'              => 'label',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729b917884a4',
						'label'             => 'Url',
						'name'              => 'url',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
					),
					array(
						'key'               => 'field_5729b935884a5',
						'label'             => 'Icons',
						'name'              => 'icons',
						'type'              => 'gallery',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'min'               => '',
						'max'               => '',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729e57022c27',
		'name'       => 'products',
		'label'      => 'Products',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'               => 'field_5729e57022c28',
				'label'             => 'Settings',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729e57022c29',
				'label'             => 'Section Name',
				'name'              => 'section_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => $is_options_page,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729e57022c2a',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729e57022c2b',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729e57022c2c',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'   => 'field_5729e57022c2d',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'               => 'field_5729e57022c2e',
				'label'             => 'Products',
				'name'              => 'products',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729e57022c2f',
				'label'             => 'Products',
				'name'              => 'products_array',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add product',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729e57022c30',
						'label'             => 'Title',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729e57022c31',
						'label'             => 'Icon',
						'name'              => 'icon',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_5729e57022c32',
						'label'             => 'Content',
						'name'              => 'content',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729d1eecc7f4',
		'name'       => 'plans',
		'label'      => 'Plans',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5729d1eecc7f5',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'      => 'field_5729d1eecc7f6',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'               => 'field_5729d1eecc7f7',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729d1eecc7f8',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729d1eecc7f9',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729d1eecc7fa',
				'label'             => 'Description',
				'name'              => 'description',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
			),
			array(
				'key'               => 'field_5729d1eecc7fb',
				'label'             => 'Options',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'           => 'field_5729d1ehcc7f9',
				'label'         => 'Table title',
				'name'          => 'table_title',
				'type'          => 'text',
				'default_value' => 'Choose a plan',
			),
			array(
				'key'               => 'field_5729d1eecc7fc',
				'label'             => 'Options',
				'name'              => 'options',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add variant',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729d1eecc7fd',
						'label'             => 'Title',
						'name'              => 'option_title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
			),
			array(
				'key'               => 'field_5729d25ecc803',
				'label'             => 'Plans',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729d274cc804',
				'label'             => 'Plans',
				'name'              => 'plans',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => 1,
				'max'               => 3,
				'layout'            => 'block',
				'button_label'      => 'Add plan',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729d28ecc805',
						'label'             => 'Text',
						'name'              => 'plan_title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729d6718f0df',
						'label'             => 'Order url',
						'name'              => 'plan_order_url',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
					),
					array(
						'key'           => 'field_5729d2918f1df',
						'label'         => 'Order label',
						'name'          => 'plan_order_label',
						'type'          => 'text',
						'default_value' => 'Order now',
					),
					array(
						'key'               => 'field_5729d398dfdf5',
						'label'             => 'Plan options',
						'name'              => 'plan_options',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'collapsed'         => '',
						'min'               => '',
						'max'               => '',
						'layout'            => 'block',
						'button_label'      => 'Add option',
						'sub_fields'        => array(
							array(
								'key'               => 'field_5729d3dfdfdf6',
								'label'             => 'Option',
								'name'              => 'option_value',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'tabs'              => 'all',
								'toolbar'           => 'full',
								'media_upload'      => 1,
							),
							array(
								'key'               => 'field_5729d619c2b65',
								'label'             => 'Class',
								'name'              => 'option_class',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'maxlength'         => '',
								'readonly'          => 0,
								'disabled'          => 0,
							),
						),
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729df524ad34',
		'name'       => 'help',
		'label'      => 'Help',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'               => 'field_5729df524ad35',
				'label'             => 'Settings',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729df524ad36',
				'label'             => 'Section Name',
				'name'              => 'section_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => $is_options_page,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729df524ad37',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729df524ad38',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729df524ad39',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'   => 'field_5729df524ad3a',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'               => 'field_5729df524ad3b',
				'label'             => 'Items',
				'name'              => 'items',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729df864ad45',
				'label'             => 'Help Items',
				'name'              => 'help_items',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add help item',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729dfa44ad46',
						'label'             => 'Icon',
						'name'              => 'help_icon',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_5729dfbc4ad47',
						'label'             => 'Title',
						'name'              => 'help_title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729e17581ca4',
						'label'             => 'Url',
						'name'              => 'help_url',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729f04031779',
		'name'       => 'case-study',
		'label'      => 'Case Study',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'               => 'field_5729f0403177a',
				'label'             => 'Settings',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729f0403177b',
				'label'             => 'Section Name',
				'name'              => 'section_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => $is_options_page,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729f0403177c',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729f0403177d',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729f0403177e',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729f0b931785',
				'label'             => 'Content',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729f0ca31786',
				'label'             => 'Content',
				'name'              => 'content',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
			),
			array(
				'key'               => 'field_5729f0d431787',
				'label'             => 'Url Label',
				'name'              => 'url_label',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729f0dd31788',
				'label'             => 'Url',
				'name'              => 'url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
			array(
				'key'               => 'field_5729f1f6f1c3d',
				'label'             => 'Block Info',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729f200f1c3e',
				'label'             => 'Image',
				'name'              => 'block_info_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'full',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5729f222f1c3f',
				'label'             => 'Info title',
				'name'              => 'info_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729f238f1c40',
				'label'             => 'Items',
				'name'              => 'delivered_items',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'table',
				'button_label'      => 'Add Row',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729f248f1c41',
						'label'             => 'Image',
						'name'              => 'image',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_5729f259f1c42',
						'label'             => 'Title',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
			),
			array(
				'key'               => 'field_5729f4d9307db',
				'label'             => 'Comments',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729f423588f2',
				'label'             => 'Comments',
				'name'              => 'comments',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add comment',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729f43f588f5',
						'label'             => 'Comment',
						'name'              => 'comment',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'maxlength'         => '',
						'rows'              => '',
						'new_lines'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_5729f423588f3',
						'label'             => 'Author',
						'name'              => 'author',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729b3fa0c142',
		'name'       => 'clients',
		'label'      => 'Clients',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'               => 'field_5729b3fa0c143',
				'label'             => 'Settings',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b3fa0c144',
				'label'             => 'Section Name',
				'name'              => 'section_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => $is_options_page,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729b3fa0c145',
				'label'             => 'Heading',
				'name'              => 'heading',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b3fa0c147',
				'label'             => 'Title',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'   => 'field_5729b3fa0c148',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'               => 'field_5729b3fa0c149',
				'label'             => 'Items',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b3fa0c14a',
				'label'             => 'Clients Items',
				'name'              => 'clients_items',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add client',
				'sub_fields'        => array(
					array(
						'key'               => 'field_5729b3fa0c14d',
						'label'             => 'Logo',
						'name'              => 'logo',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
				),
			),
			array(
				'key'               => 'field_5729b5675b555',
				'label'             => 'Button',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5729b5715b556',
				'label'             => 'Label',
				'name'              => 'label',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5729b5785b557',
				'label'             => 'Url',
				'name'              => 'url',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
			),
		),
		'min'        => '',
		'max'        => '',
	);
	$layouts[] = array(
		'key'        => '5729b3fb8c142',
		'name'       => 'pricing',
		'label'      => 'Pricing',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_57h9d1eecc7f5',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'      => 'field_5h29d1eecc7f6',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'   => 'field_572bad53a84b9',
				'label' => 'Heading',
				'type'  => 'tab',
			),
			array(
				'key'   => 'field_572bad6da84ba',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572bad73a84bb',
				'label' => 'Subtitle',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572bad7ca84bc',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'   => 'field_572bae729c408',
				'label' => 'Prices',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_572bad99a84bd',
				'label'        => 'Prices',
				'name'         => 'prices',
				'type'         => 'repeater',
				'required'     => 1,
				'layout'       => 'block',
				'button_label' => 'Add price',
				'sub_fields'   => array(
					array(
						'key'      => 'field_572bada8a84be',
						'label'    => 'Title',
						'name'     => 'title',
						'type'     => 'text',
						'required' => 1,
					),
					array(
						'key'           => 'field_572badd5a84bf',
						'label'         => 'Currency',
						'name'          => 'currency',
						'type'          => 'text',
						'required'      => 1,
						'default_value' => '$',
					),
					array(
						'key'      => 'field_572badffa84c0',
						'label'    => 'Price',
						'name'     => 'price',
						'type'     => 'number',
						'required' => 1,
					),
					array(
						'key'           => 'field_572bae13a84c2',
						'label'         => 'After',
						'name'          => 'after',
						'type'          => 'text',
						'required'      => 1,
						'default_value' => '/mo',
					),
					array(
						'key'   => 'field_572bae2ba84c3',
						'label' => 'Button Label',
						'name'  => 'button_label',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_572bae3ba84c4',
						'label' => 'Button Url',
						'name'  => 'button_url',
						'type'  => 'text',
					),
				),
			),
			array(
				'key'               => 'field_572baf2eef21b',
				'label'             => 'Bundles',
				'name'              => 'bundles',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_572baf83ef21f',
				'label'             => 'Title',
				'name'              => 'bundles_title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_572baf39ef21c',
				'label'             => 'Description',
				'name'              => 'bundles_description',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => 'br',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_572baf6cef21d',
				'label'             => 'Bundles',
				'name'              => 'bundles_list',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add bundle',
				'sub_fields'        => array(
					array(
						'key'               => 'field_572baf77ef21e',
						'label'             => 'Title',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_572baf9fef220',
						'label'             => 'Content',
						'name'              => 'content',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
					),
					array(
						'key'               => 'field_572bafa7ef221',
						'label'             => 'Image',
						'name'              => 'icon',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
				),
			),
		)
	);
	$layouts[] = array(
		'key'        => '5729b3vb8c842',
		'name'       => 'use-case',
		'label'      => 'Use Case',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_57x9d1eecc7f5',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'      => 'field_572vd1eecc7f6',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'   => 'field_572cde0136a0b',
				'label' => 'Heading',
				'type'  => 'tab',
			),
			array(
				'key'               => 'field_572cde0f36a0c',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_572cde1836a0d',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'   => 'field_572cde1e36a0e',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'               => 'field_572cdf1f68a3c',
				'label'             => 'Details',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_572cdf2968a3d',
				'label'             => 'Content',
				'name'              => 'content',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
			),
			array(
				'key'               => 'field_572cdf5c68a3e',
				'label'             => 'Image',
				'name'              => 'image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'full',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
		)
	);
	$layouts[] = array(
		'key'        => '5729b5vb8c842',
		'name'       => 'products-2',
		'label'      => 'Products v2',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_5799d1eecc7f5',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'      => 'field_5749d1eecc7f6',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'       => 'field_57ccde0136a0b',
				'label'     => 'Heading',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'               => 'field_5v2cde1836a0d',
				'label'             => 'Title',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_572cdf8cf3836',
				'label'             => 'Products',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_572cdfa6f3838',
				'label'             => 'Products',
				'name'              => 'products_list',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'block',
				'button_label'      => 'Add product',
				'sub_fields'        => array(
					array(
						'key'               => 'field_572cdfbbf3839',
						'label'             => 'Title',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_572cdfc1f383a',
						'label'             => 'Image',
						'name'              => 'image',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'url',
						'preview_size'      => 'full',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
					array(
						'key'               => 'field_572cdfd3f383b',
						'label'             => 'Url',
						'name'              => 'url',
						'type'              => 'url',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
					),
				),
			),
			array(
				'key'       => 'field_57cc7e0136a0b',
				'label'     => 'Button',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'   => 'field_572cdfbbf7839',
				'label' => 'Button Label',
				'name'  => 'button_label',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572cd5d3f383b',
				'label' => 'Button Url',
				'name'  => 'button_url',
				'type'  => 'url',
			),
		),
	);
	$layouts[] = array(
		'key'        => '5729b56b8c842',
		'name'       => 'questions',
		'label'      => 'Questions',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_57c9d1eecc7f5',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'      => 'field_5789d1eecc7f6',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'   => 'field_572cde0236a0b',
				'label' => 'Heading',
				'type'  => 'tab',
			),
			array(
				'key'   => 'field_572cde183620d',
				'label' => 'Title',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572cde1e3620e',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'       => 'field_5729d25vcc803',
				'label'     => 'Button',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_5729d6728f0df',
				'label' => 'Url',
				'name'  => 'questions_url',
				'type'  => 'url',

			),
			array(
				'key'           => 'field_5729d5918f1df',
				'label'         => 'Label',
				'name'          => 'questions_label',
				'type'          => 'text',
				'default_value' => 'Chat With Us',
			),
		),
	);
	$layouts[] = array(
		'key'        => '5720b56b8c842',
		'name'       => 'product',
		'label'      => 'Product',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_572dd671ecd61',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'      => 'field_572dd679ecd62',
				'label'    => 'Section Name',
				'name'     => 'section_name',
				'type'     => 'text',
				'required' => $is_options_page,
			),
			array(
				'key'       => 'field_572cf2f7c32de',
				'label'     => 'Heading',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_572cf301c32df',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572cf322c32e0',
				'label' => 'Subtitle',
				'name'  => 'subtitle',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572cf328c32e1',
				'label' => 'Description',
				'name'  => 'description',
				'type'  => 'wysiwyg',
			),
			array(
				'key'       => 'field_572cf343c32e2',
				'label'     => 'Buttons',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'          => 'field_572cf34fc32e3',
				'label'        => 'Buttons',
				'name'         => 'buttons',
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => 'Add button',
				'sub_fields'   => array(
					array(
						'key'      => 'field_572cf35fc32e4',
						'label'    => 'Label',
						'name'     => 'label',
						'type'     => 'text',
						'required' => 1,
					),
					array(
						'key'   => 'field_572cf363c32e5',
						'label' => 'Url',
						'name'  => 'url',
						'type'  => 'url',
					),
				),
			),
			array(
				'key'       => 'field_572cf3be95222',
				'label'     => 'Products',
				'name'      => 'products',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_572cf3e995224',
				'label' => 'Section title',
				'name'  => 'section_title',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_572dd715464d3',
				'label' => 'First column title',
				'name'  => 'first_column_title',
				'type'  => 'text',
			),
			array(
				'key'          => 'field_572dd78c24170',
				'label'        => 'Products',
				'name'         => 'products_list_product',
				'type'         => 'repeater',
				'required'     => 1,
				'min'          => 1,
				'max'          => 3,
				'layout'       => 'table',
				'button_label' => 'Add product',
				'sub_fields'   => array(
					array(
						'key'           => 'field_572dd7f924171',
						'label'         => 'Icon',
						'name'          => 'icon',
						'type'          => 'image',
						'required'      => 1,
						'return_format' => 'url',
						'preview_size'  => 'full',
						'library'       => 'all',
					),
					array(
						'key'      => 'field_572dd80624172',
						'label'    => 'Title',
						'name'     => 'title',
						'type'     => 'text',
						'required' => 1,
					),
				),
			),
			array(
				'key'       => 'field_572dd72d464d4',
				'label'     => 'Options',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'          => 'field_572cf4cff2af8',
				'label'        => 'Product table',
				'name'         => 'product_table',
				'type'         => 'repeater',
				'required'     => 1,
				'layout'       => 'block',
				'button_label' => 'Add option',
				'sub_fields'   => array(
					array(
						'key'   => 'field_572dd904c402b',
						'label' => 'Option Title',
						'name'  => 'option_title',
						'type'  => 'tab',
					),
					array(
						'key'   => 'field_572cf4f2f2af9',
						'label' => 'Option Title',
						'name'  => 'option_title',
						'type'  => 'text',
					),
					array(
						'key'           => 'field_572dde051e39f',
						'label'         => 'Subheading',
						'name'          => 'option_subheading',
						'type'          => 'true_false',
						'message'       => 'Set as subheading',
						'default_value' => 0,
					),
					array(
						'key'       => 'field_572dd923c402c',
						'label'     => 'Column 1',
						'type'      => 'tab',
						'placement' => 'top',
						'endpoint'  => 0,
					),
					array(
						'key'           => 'field_572dd880ce583',
						'label'         => 'Type Column',
						'name'          => 'type_column_1',
						'type'          => 'select',
						'choices'       => array(
							'empty'       => 'Empty',
							'yes'         => 'Yes',
							'custom_text' => 'Custom text',
						),
						'default_value' => array(
							0 => 'yes',
						),
					),
					array(
						'key'               => 'field_572dd8c0ce584',
						'label'             => 'Custom Text',
						'name'              => 'custom_text_column_1',
						'type'              => 'text',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_572dd880ce583',
									'operator' => '==',
									'value'    => 'custom_text',
								),
							),
						),
						'default_value'     => 'Optional',
					),
					array(
						'key'       => 'field_572dd978d5f77',
						'label'     => 'Column 2',
						'type'      => 'tab',
						'placement' => 'top',
						'endpoint'  => 0,
					),
					array(
						'key'           => 'field_572dd9e3b0af8',
						'label'         => 'Type Column',
						'name'          => 'type_column_2',
						'type'          => 'select',
						'choices'       => array(
							'empty'       => 'Empty',
							'yes'         => 'Yes',
							'custom_text' => 'Custom text',
						),
						'default_value' => array(
							0 => 'yes',
						),
					),
					array(
						'key'               => 'field_572dd9f3b0af9',
						'label'             => 'Custom Text',
						'name'              => 'custom_text_column_2',
						'type'              => 'text',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_572dd9e3b0af8',
									'operator' => '==',
									'value'    => 'custom_text',
								),
							),
						),
						'default_value'     => 'Optional',
					),
					array(
						'key'       => 'field_572dd97bd5f78',
						'label'     => 'Column 3',
						'type'      => 'tab',
						'placement' => 'top',
						'endpoint'  => 0,
					),
					array(
						'key'           => 'field_572dda3c2687d',
						'label'         => 'Type Column',
						'name'          => 'type_column_3',
						'type'          => 'select',
						'choices'       => array(
							'empty'       => 'Empty',
							'yes'         => 'Yes',
							'custom_text' => 'Custom text',
						),
						'default_value' => array(
							0 => 'yes',
						),
					),
					array(
						'key'               => 'field_572dda5b2687e',
						'label'             => 'Custom Text',
						'name'              => 'custom_text_column_3',
						'type'              => 'text',
						'required'          => 1,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_572dda3c2687d',
									'operator' => '==',
									'value'    => 'custom_text',
								),
							),
						),
						'default_value'     => 'Optional',
					),
				),
			),
		),
	);
	$layouts[] = array(
		'key'        => '5720c66b8c842',
		'name'       => 'two-column-content',
		'label'      => 'II Column Content',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_572df4b178eca',
				'label'     => 'Settings',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'           => 'field_572df51478ecd',
				'label'         => 'Background Image',
				'name'          => 'background_image',
				'type'          => 'image',
				'return_format' => 'url',
				'preview_size'  => 'full',
				'library'       => 'all',
			),
			array(
				'key'   => 'field_572df93c015c2',
				'label' => 'Background Color',
				'name'  => 'background_color',
				'type'  => 'color_picker',
			),
			array(
				'key'   => 'field_572df4c978ecb',
				'label' => 'Section Name',
				'name'  => 'section_name',
				'type'  => 'text',
			),
			array(
				'key'       => 'field_572df4f878ecc',
				'label'     => 'Heading',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'   => 'field_572df55f78ecf',
				'label' => 'Title',
				'name'  => 'title',
				'type'  => 'text',
			),
			array(
				'key'       => 'field_572df56378ed0',
				'label'     => 'Content',
				'type'      => 'tab',
				'placement' => 'top',
				'endpoint'  => 0,
			),
			array(
				'key'          => 'field_572df56d78ed1',
				'label'        => 'Text Left',
				'name'         => 'text_left',
				'type'         => 'wysiwyg',
				'tabs'         => 'all',
				'toolbar'      => 'full',
				'media_upload' => 1,
			),
			array(
				'key'          => 'field_572df57c78ed2',
				'label'        => 'Text Right',
				'name'         => 'text_right',
				'type'         => 'wysiwyg',
				'tabs'         => 'all',
				'toolbar'      => 'full',
				'media_upload' => 1,
			),
		)
	);

	if ( ! $is_options_page ) {
		$layouts[] = array(
			'key'        => '5729a65be60d0',
			'name'       => 'defined-section',
			'label'      => 'Defined Section',
			'display'    => 'block',
			'sub_fields' => array(
				array(
					'key'      => 'field_5729a66ae60d1',
					'label'    => 'Section',
					'name'     => 'section_defined',
					'type'     => 'select',
					'required' => 1,
					'choices'  => get_defined_sections_list(),
				),
			),
			'min'        => '',
			'max'        => '',
		);
	}

	if ( function_exists( 'acf_add_local_field_group' ) ) {
		//Social Widget
		acf_add_local_field_group( array(
			'key'                   => 'group_57274d9ba1838',
			'title'                 => 'Social Widget',
			'fields'                => array(
				array(
					'key'               => 'field_57274dabc8e6a',
					'label'             => 'Socials',
					'name'              => 'socials',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => '',
					'max'               => '',
					'layout'            => 'block',
					'button_label'      => 'Add social',
					'sub_fields'        => array(
						array(
							'key'               => 'field_57274dd1c8e6c',
							'label'             => 'Url',
							'name'              => 'url',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5727526f6ce8f',
							'label'             => 'Class',
							'name'              => 'classes',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'readonly'          => 0,
							'disabled'          => 0,
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'widget',
						'operator' => '==',
						'value'    => 'ic_social',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		) );

		//Flexible Content
		acf_add_local_field_group( array(
			'key'                   => 'group_5728f37c98dde',
			'title'                 => 'Flexible Content',
			'fields'                => array(
				array(
					'key'               => 'field_5729a1d85ae18',
					'label'             => 'Content',
					'name'              => $name,
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'button_label'      => 'Add section',
					'min'               => '',
					'max'               => '',
					'layouts'           => $layouts,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'template-pages/flexible-content.php',
					),
				),
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'defined-sections',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'the_content',
				1  => 'excerpt',
				2  => 'custom_fields',
				3  => 'discussion',
				4  => 'comments',
				5  => 'revisions',
				6  => 'slug',
				7  => 'author',
				8  => 'format',
				9  => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
			'active'                => 1,
			'description'           => '',
		) );
	}
}

add_action( 'after_setup_theme', 'ic_theme_custom_fields' );

function ic_save_flexible_content( $post_id ) {

	if ( wp_is_post_revision( $post_id ) ) {
		return;
	}

	if ( 'auto-draft' == get_post_status( $post_id ) ) {
		return;
	}
	if ( get_page_template_slug( $post_id ) !== 'template-pages/flexible-content.php' ) {
		return;
	}

	ob_start();

	ic_get_flexible_content( $post_id );

	$content = ob_get_clean();

	wp_update_post( array(
		'ID'           => $post_id,
		'post_content' => wp_strip_all_tags( $content, true ),
	) );
}

add_action( 'acf/save_post', 'ic_save_flexible_content', 50 );
